openbeers_address: http://openbeers.hopto.org

dest_folder: temp/
input_dir: Input/
output_dir: Output/

simulation_name: val_de_bagnes_148_climate_contemporary_pv_roof_2025
municipalities_file: municipalities-data-2025.csv
tarifs_file: elcom-data-2025.csv

needed_series:
  - Qs
  - SolarPVProduction
  - ElectricConsumption

needed_attributes:
  - gbez
  - PostCode
  - num_floors
  - egid
  - area
  - habitable_surface
  - building_type
  - gebaeude_nutzung
  - TotalPower
  - MainCategory
  - SubCategory
  - Municipality

