openbeers_address: https://lab.idiap.ch/openbeers

dest_folder: temp/
input_dir: Input/
output_dir: Output/

loop_mode: False
simulation_name: val_de_bagnes_41_climate_contemporary_pv_roof_2025
# simulation_name: val_de_bagnes_201_climate_rcp85_pv_none_2040
simulation_extraction_dir: outputs_extraction/
basopra_output_dir: outputs_basopra/
municipalities_file: municipalities-data-2025.csv
tarifs_file: elcom-data-2025.csv

building_aggregation: True
building_separation: False  # TODO Make sure that if this is False we don't recompute the individual buildings

needed_series:
  - Qs
  - SolarPVProduction
  - ElectricConsumption

needed_attributes:
  - gbez
  - PostCode
  - num_floors
  - egid
  - area
  - habitable_surface
  - building_type
  - gebaeude_nutzung
  - TotalPower
  - MainCategory
  - SubCategory
  - Municipality

aggregation_methods:  # supports mean, median, sum, random, custom
  attributes:
    egid:               0
    bid:                0
    gbez:               null
    building_type:      null
    num_floors:         null
    area:               sum
    habitable_surface:  sum
    municipality_name:  first
    roof_surface:       sum
    roof_pv_surface:    sum
    roof_pv_capacity:   sum
    wall_surface:       sum
    wall_pv_surface:    sum
    wall_pv_capacity:   sum
    floor_surface:      sum
    floor_pv_surface:   sum
    floor_pv_capacity:  sum
    elec_price:         mean  # TODO Find a solution: Is a potential issue with varying surfaces of buildings of different types. Might need something more complex to deal with this in the future.
  series:
    DD:                   mean  # TODO Not used for now but might want to consider using it in the future
    ElectricConsumption:  sum   # Used
    FF:                   median  # TODO Not used for now
    G_Bn:                 mean
    G_Dh:                 mean
    N:                    first
    Qs:                   sum   # Used
    RH:                   mean
    RR:                   sum
    SolarPVProduction:    sum   # Used
    Ta:                   mean  # Used
    Ts:                   mean
    h:                    first
    dhw:                  sum
    dm:                   mean
    m:                    sum
  heat_pump:
    attributes:
      T_d_supply_floor:           null  # first
      T_d_return_floor:           null  # first
      T_d_supply_radiator:        null  # first
      T_d_return_radiator:        null  # first
      T_d_supply_floor_tank:      null  # first
      T_d_return_floor_tank:      null  # first
      T_d_supply_radiator_tank:   null  # first
      T_d_return_radiator_tank:   null  # first
      rad_exp_floor:              null  # first
      rad_exp_radiator:           null  # first
      buradiator:                 null  # mean
      design_temp:                null  # first
      heatload_dt:                null  # mean
      hp:                         null  # first
    series:
      Set_T:            null  # first 
      Temp:             null  # mean
      Req_kWh:          null  # sum
      Temp_supply:      null  # mean
      Temp_supply_tank: null  # mean
      COP_SH:           null  # mean
      COP_tank:         null  # mean
      COP_DHW:          null  # mean
      hp_sh_cons:       null  # sum
      hp_tank_cons:     null  # sum
      hp_dhw_cons:      null  # sum
output_aggregations:  # Uncomment the ones that you want to aggrefate from the results of the basopra optimization
  E_PV_batt:            sum
  E_PV_batt_EV:         sum
  # E_PV_bu
  # E_PV_budhw
  # E_PV_curt
  # E_PV_grid
  # E_PV_hp
  # E_PV_hpdhw
  # E_PV_load
  # E_batt_EV_bu
  # E_batt_EV_budhw
  # E_batt_EV_grid
  # E_batt_EV_hp
  # E_batt_EV_hpdhw
  # E_batt_EV_load
  # E_batt_bu
  # E_batt_budhw
  # E_batt_hp
  # E_batt_hpdhw
  # E_batt_load
  # E_bu
  # E_budhw
  # E_char
  # E_char_EV
  # E_char_away
  # E_cons
  # E_dis
  # E_dis_EV
  # E_grid_batt
  # E_grid_batt_EV
  # E_grid_bu
  # E_grid_budhw
  E_grid_hp:          sum
  E_grid_hpdhw:       sum
  # E_grid_load
  # E_hp
  # E_hpdhw
  # E_loss_Batt
  # E_loss_Batt_EV
  # E_loss_conv
  # E_loss_inv
  # E_loss_inv_PV
  # E_loss_inv_batt
  # E_loss_inv_grid
  # Q_dhwst_hd
  # Q_hp_sh
  # Q_hp_ts
  # Q_loss_dhwst
  # Q_loss_ts
  # Q_ts
  # Q_ts_delta
  # Q_ts_sh
  # SOC
  # SOC_EV
  # T_dhwst
  # T_ts
  # E_demand
  # E_PV
  # Export_price
  # price
  # Inv_P
  # Conv_P
  # Req_kWh
  # Req_kWh_DHW
  # Set_T
  # Temp
  # Temp_supply
  # Temp_supply_tank
  # T_aux_supply
  # COP_tank
  # COP_SH
  COP_DHW:            sum
  # E_EV_trip

logging:
  version: 1

  formatters:
    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    simple:
      format: '%(levelname)s - %(message)s'

  handlers:
    code_file:
      class: logging.FileHandler
      formatter: detailed
      filename: logs/openbeers.log
      level: INFO 

    data_file:
      class: logging.FileHandler
      formatter: detailed
      filename: logs/data_issues.log
      level: INFO

    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG

  loggers:
    openbeers.default:
      level: INFO 
      handlers: [code_file, console]
      propagate: no

    openbeers.data:
      level: INFO
      handlers: [data_file, console]
      propagate: no

  root:
    level: WARNING
    handlers: [console]

heat_pump:
  multiprocessing: True
  max_processes: -2 # value of null or 0 will use max possible processes. Negative value will use max processes - value

  dict_design:
    T_d_supply_floor: 35
    T_d_return_floor: 30
    T_d_supply_radiator: 50
    T_d_return_radiator: 40
    T_d_supply_floor_tank: 40
    T_d_return_floor_tank: 35
    T_d_supply_radiator_tank: 55
    T_d_return_radiator_tank: 45
    rad_exp_floor: 1.1
    rad_exp_radiator: 1.3

Core:
  oldschool: False # Testint parameter used to switch between old parameter loading style and new one for comparison purposes
  multiprocessing: True
  basopra_processes: -2 # value of null or 0 will use max possible processes. Negative value will use max processes - value

  Optimizer:
    solver_verbose: False
    solver_results_write: False

  basopra_run_combinations:
    Capacity: [7]
    App_comb: [0]
    Tech: ["NMC"]
    PV_nom: [1]
    country: ["CH"]
    cases: ["mean"]
    house_type: ["SFH100"]
    HP: ["AS"]
    conf: [0, 4]  # 0 only HP; 1 HP+DHW; 2 HP+SH; 3 HP+SH+DHW; 4 only Battery; 5 HP+DHW+BATT; 6 HP+SH+BATT; 7 HP+SH+DHW+BATT
    EV_V2G: [0]
    electricity_profile: ["High"]
    EV_batt_cap: [60]
    EV_P_max_home: ["11"]
    EV_use: ["Low"]
    profile_row_number: [99]
  
  mapping:
    0: '0100'
    1: '0101'
    2: '0110'
    3: '0111'
    4: '1100'
    5: '1101'
    6: '1110'
    7: '1111'
  
  reverse_mapping:
    '0100': 0
    '0101': 1
    '0110': 2
    '0111': 3
    '1100': 4
    '1101': 5
    '1110': 6
    '1111': 7
  
  conf_mapping:
    0: 'only HP'
    1: 'HP+DHW'
    2: 'HP+SH'
    3: 'HP+SH+DHW'
    4: 'only Battery'
    5: 'HP+DHW+BATT'
    6: 'HP+SH+BATT'
    7: 'HP+SH+DHW+BATT'
  
  basopra_fixed_parameters:
    App_comb: 0
    Tech: 'NMC'
    PV_nom: 1
    country: 'CH'
    cases: 'mean'
    house_type: 'SFH100'
    HP: 'AS'
    EV_V2G: 0
    electricity_profile: 'High'
    EV_batt_cap: 60
    EV_P_max_home: '11'
    EV_use: 'High'
    profile_row_number: 99
  
  param_load_fixed_parameters:
    aging: False
    Curtailment: 0
    Inverter_efficiency: 0.95
    Converter_efficiency_HP: 0.98
    delta_t: 1
    Capacity_tariff: 0
    nyears: 1
    days: 365
    testing: False

