openbeers_address: https://lab.idiap.ch/openbeers

dest_folder: temp/
input_dir: Input/
output_dir: Output/
no_cache: False

loop_mode: False

multiprocessing: False
max_processes: -2 # value of null or 0 will use max possible processes. Negative value will use max processes - value

simulation_names: 
#  - val_de_bagnes_41_climate_contemporary_pv_none_2025
  - val_de_bagnes_41_climate_contemporary_pv_roof_2025
#   - val_de_bagnes_41_climate_rcp26_pv_none_2040
#   - val_de_bagnes_41_climate_rcp26_pv_none_2050
#   - val_de_bagnes_41_climate_rcp26_pv_roof_2040
#   - val_de_bagnes_41_climate_rcp26_pv_roof_2050
#   - val_de_bagnes_41_climate_rcp26_pv_roof_walls_2040
#   - val_de_bagnes_41_climate_rcp26_pv_roof_walls_2050
#   - val_de_bagnes_41_climate_rcp85_pv_none_2040
#   - val_de_bagnes_41_climate_rcp85_pv_none_2050
#   - val_de_bagnes_41_climate_rcp85_pv_roof_2040
#   - val_de_bagnes_41_climate_rcp85_pv_roof_2050
#   - val_de_bagnes_41_climate_rcp85_pv_roof_walls_2040
#   - val_de_bagnes_41_climate_rcp85_pv_roof_walls_2050

building_blacklist:
  - 902139
  - 902141
  - 902142
# simulation_name: val_de_bagnes_201_climate_rcp85_pv_none_2040
simulation_extraction_dir: outputs_extraction/
basopra_output_dir: outputs_basopra/
municipalities_file: municipalities-data-2025.csv
tarifs_file: elcom-data-2025.csv

building_aggregation: False
building_separation: False  # TODO Make sure that if this is False we don't recompute the individual buildings

needed_series:
  - Qs
  - SolarPVProduction
  - ElectricConsumption

needed_attributes:
  - gbez
  - PostCode
  - num_floors
  - egid
  - area
  - habitable_surface
  - building_type
  - gebaeude_nutzung
  - TotalPower
  - MainCategory
  - SubCategory
  - Municipality
  - commune
  - plz_plz6

heat_pump:
  dict_design:
    T_d_supply_floor: 35
    T_d_return_floor: 30
    T_d_supply_radiator: 50
    T_d_return_radiator: 40
    T_d_supply_floor_tank: 40
    T_d_return_floor_tank: 35
    T_d_supply_radiator_tank: 55
    T_d_return_radiator_tank: 45
    rad_exp_floor: 1.1
    rad_exp_radiator: 1.3

Core:
  Optimizer:
    solver_verbose: False
    solver_results_write: False
    
  mapping:
    0:  '0100'
    1:  '0101'
    2:  '0110'
    3:  '0111'
    4:  '1100'
    5:  '1101'
    6:  '1110'
    7:  '1111'
    8:  '0000'
    9:  '0001'
    10: '0010'
    11: '0011'
    12: '1000'
    13: '1001'
    14: '1010'
    15: '1011'
  
  reverse_mapping:
    '0100': 0  
    '0101': 1  
    '0110': 2  
    '0111': 3  
    '1100': 4  
    '1101': 5  
    '1110': 6  
    '1111': 7  
    '0000': 8  
    '0001': 9  
    '0010': 10 
    '0011': 11 
    '1000': 12 
    '1001': 13 
    '1010': 14 
    '1011': 15 
  
  conf_mapping:
    0: 'only HP'
    1: 'HP+DHW'
    2: 'HP+SH'
    3: 'HP+SH+DHW'
    4: 'HP+BATT'
    5: 'HP+DHW+BATT'
    6: 'HP+SH+BATT'
    7: 'HP+SH+DHW+BATT'
    8: 'Nothing'
    9: 'DHW'
    10: 'SH'
    11: 'SH+DHW'
    12: 'only Battery'
    13: 'DHW+BATT'
    14: 'SH+BATT'
    15: 'SH+DHW+BATT'

  
  basopra_fixed_parameters:
    App_comb: 0
    Tech: 'NMC'
    PV_nom: 1
    country: 'CH'
    cases: 'mean'
    house_type: 'NoHeatPump' # 'SFH100'
    HP: 'AS'
    EV_V2G: 0
    electricity_profile: 'High'
    # EV_batt_cap: 60
    # EV_P_max_home: '11'
    # EV_use: 'High'
    profile_row_number: 99
    sizing_tank: 15
  
  param_load_fixed_parameters:
    aging: False
    Curtailment: 0
    Inverter_efficiency: 0.95
    Converter_efficiency_batt: 0.98
    delta_t: 1
    Capacity_tariff: 0
    nyears: 1
    days: 365
    testing: False

  basopra_run_combinations:
    Capacity: [7]
    App_comb: [0]
    Tech: ["NMC"]
    PV_nom: [1]
    country: ["CH"]
    cases: ["mean"]
    house_type: ['NoHeatPump'] # ["SFH100"] ['NoHeatPump','SFH100']
    HP: ["AS"]
    conf: [7]  # 0 only HP; 1 HP+DHW; 2 HP+SH; 3 HP+SH+DHW; 4 only Battery + HP; 5 HP+DHW+BATT; 6 HP+SH+BATT; 7 HP+SH+DHW+BATT
    ev_profiles:
      EV1:
        EV_batt_cap:     0
        EV_P_max_home:  '7'
        EV_use:         'High'
        profile_row_number: 99
#      EV2:
#        EV_batt_cap:     60
#        EV_P_max_home:  '11'
#        EV_use:         'High'
#        profile_row_number: 98