openbeers_address: https://lab.idiap.ch/openbeers

dest_folder: temp/
input_dir: Input/
output_dir: Output/

loop_mode: True
# simulation_name: val_de_bagnes_41_climate_contemporary_pv_roof_2025
simulation_name: val_de_bagnes_201_climate_rcp85_pv_none_2040
simulation_extraction_dir: outputs_extraction/
basopra_output_dir: outputs_basopra/
municipalities_file: municipalities-data-2025.csv
tarifs_file: elcom-data-2025.csv

extraction:
  zone_aggregated_buildings: True

needed_series:
  - Qs
  - SolarPVProduction
  - ElectricConsumption

needed_attributes:
  - gbez
  - PostCode
  - num_floors
  - egid
  - area
  - habitable_surface
  - building_type
  - gebaeude_nutzung
  - TotalPower
  - MainCategory
  - SubCategory
  - Municipality

logging:
  version: 1

  formatters:
    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    simple:
      format: '%(levelname)s - %(message)s'

  handlers:
    code_file:
      class: logging.FileHandler
      formatter: detailed
      filename: logs/openbeers.log
      level: INFO 

    data_file:
      class: logging.FileHandler
      formatter: detailed
      filename: logs/data_issues.log
      level: INFO

    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG

  loggers:
    openbeers.default:
      level: INFO 
      handlers: [code_file, console]
      propagate: no

    openbeers.data:
      level: INFO
      handlers: [data_file, console]
      propagate: no

  root:
    level: WARNING
    handlers: [console]

heat_pump:
  multiprocessing: True
  max_processes: -2 # value of null or 0 will use max possible processes. Negative value will use max processes - value

  dict_design:
    T_d_supply_floor: 35
    T_d_return_floor: 30
    T_d_supply_radiator: 50
    T_d_return_radiator: 40
    T_d_supply_floor_tank: 40
    T_d_return_floor_tank: 35
    T_d_supply_radiator_tank: 55
    T_d_return_radiator_tank: 45
    rad_exp_floor: 1.1
    rad_exp_radiator: 1.3

Core:
  oldschool: False # Testint parameter used to switch between old parameter loading style and new one for comparison purposes
  multiprocessing: True
  basopra_processes: -2 # value of null or 0 will use max possible processes. Negative value will use max processes - value

  Optimizer:
    solver_verbose: False
    solver_results_write: False

  basopra_run_combinations:
    Capacity: [7]
    App_comb: [0]
    Tech: ["NMC"]
    PV_nom: [1]
    country: ["CH"]
    cases: ["mean"]
    house_type: ["SFH100"]
    HP: ["AS"]
    conf: [0, 4]  # 0 only HP; 1 HP+DHW; 2 HP+SH; 3 HP+SH+DHW; 4 only Battery; 5 HP+DHW+BATT; 6 HP+SH+BATT; 7 HP+SH+DHW+BATT
    EV_V2G: [0]
    electricity_profile: ["High"]
    EV_batt_cap: [60]
    EV_P_max_home: ["11"]
    EV_use: ["Low"]
    profile_row_number: [99]
  
  mapping:
    0: '0100'
    1: '0101'
    2: '0110'
    3: '0111'
    4: '1100'
    5: '1101'
    6: '1110'
    7: '1111'
  
  reverse_mapping:
    '0100': 0
    '0101': 1
    '0110': 2
    '0111': 3
    '1100': 4
    '1101': 5
    '1110': 6
    '1111': 7
  
  conf_mapping:
    0: 'only HP'
    1: 'HP+DHW'
    2: 'HP+SH'
    3: 'HP+SH+DHW'
    4: 'only Battery'
    5: 'HP+DHW+BATT'
    6: 'HP+SH+BATT'
    7: 'HP+SH+DHW+BATT'
  
  basopra_fixed_parameters:
    App_comb: 0
    Tech: 'NMC'
    PV_nom: 1
    country: 'CH'
    cases: 'mean'
    house_type: 'SFH100'
    HP: 'AS'
    EV_V2G: 0
    electricity_profile: 'High'
    EV_batt_cap: 60
    EV_P_max_home: '11'
    EV_use: 'High'
    profile_row_number: 99
  
  param_load_fixed_parameters:
    aging: False
    Curtailment: 0
    Inverter_efficiency: 0.95
    Converter_efficiency_HP: 0.98
    delta_t: 1
    Capacity_tariff: 0
    nyears: 1
    days: 365
    testing: False

